# Generated by Django 4.1.7 on 2023-04-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magasin", "0029_alter_produit_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="fournisseur",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
